#Target
PROGRAMS_spu := ApplyThresholding ApplyKernal 
LIBRARY_embed := lib_ApplyThresholding.a lib_ApplyKernal.a
CC_OPT_LEVEL = -g -O0

#buildutils/make.footer
include $(CELL_TOP)/buildutils/make.footer
